export const TITLE_PAGES = {
    CREATE_PRODUCT: "ADD NEW PRODUCT",
    MANAGE_PRODUCTS: "MANAGE LIST PRODUCTS",
    UPDATE_PRODUCT: "UPDATE PRODUCT",
    PRODUCT_DETAIL: "PRODUCT DETAILS",
    LIST_PRODUCTS: "LIST PRODUCTS",
};

export const ROLE_USERS = {
    USER: "USER",
    ADMIN: "ADMIN",
};

export const MODE_LIST_PRODUCTS = {
    VIEW: "VIEW",
    MANAGE: "MANAGE",
};
